'use client';
import {useState} from 'react';
import type {Template} from '@/lib/model';
import {placementFrom,type Placement} from '@/types/images';
import {Dialog,Spinner} from '@/components/ui';
export function PlacementEditor({template,onClose,onSave}:{template:Template;onClose:()=>void;onSave:(placement:Placement)=>Promise<void>}){
 const [placement,setPlacement]=useState(placementFrom(template.placement)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Dialog title="Posición de la persona" onClose={onClose}><div className="placement-preview"><img src={template.url} alt="Escenario de referencia"/><div className="placement-box" style={{left:`${placement.x*100}%`,top:`${placement.y*100}%`,width:`${placement.width*100}%`,height:`${placement.height*100}%`,transform:`rotate(${placement.rotation}deg)`}}>TU FOTO</div></div><form onSubmit={async event=>{event.preventDefault();setBusy(true);try{await onSave(placementFrom(placement));}catch{setError('No pudimos guardar la posición.');}finally{setBusy(false);}}}><div className="placement-fields">{([{key:'x',label:'Posición horizontal',max:.9},{key:'y',label:'Posición vertical',max:.9},{key:'width',label:'Ancho',max:1},{key:'height',label:'Alto',max:1},{key:'rotation',label:'Rotación',max:30}] as const).map(field=><label key={field.key}>{field.label}<input aria-label={field.label} type="range" min={field.key==='rotation'?-30:0} max={field.max} step={field.key==='rotation'?1:.01} value={placement[field.key]} onChange={event=>setPlacement(p=>placementFrom({...p,[field.key]:Number(event.target.value)}))}/></label>)}</div><label className="field">Recorte<select value={placement.preferred_crop} onChange={e=>setPlacement({...placement,preferred_crop:e.target.value==='cover'?'cover':'contain'})}><option value="contain">Mantener persona completa</option><option value="cover">Llenar espacio</option></select></label><label className="field">Indicaciones<textarea maxLength={500} value={placement.description} onChange={e=>setPlacement({...placement,description:e.target.value})}/></label>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?<Spinner/>:'Guardar posición'}</button></div></form></Dialog>;
}
