export function generationError(code:string|null|undefined,fallback='No pudimos crear tu foto. Puedes volver a intentarlo.'){
 const messages:Record<string,string>={
  LOCAL_MONTAGE_REQUIRED:'Selecciona tu foto y prepara el montaje en el editor antes de guardarlo.',
  PHOTO_FACE_TOO_SMALL:'Tu rostro se ve demasiado pequeño. Usa la foto original, acércate a la cámara y evita capturas de pantalla.',
  PHOTO_FACE_BLURRY:'El rostro está borroso o perdió detalle. Sube una foto original más nítida, sin filtros ni ampliaciones.',
  PHOTO_CHECK_UNAVAILABLE:'No pudimos completar la revisión de calidad. No entregaremos un resultado sin revisar. Inténtalo de nuevo.',
  PHOTO_RESULT_BLURRY:'El rostro generado quedó demasiado pequeño o borroso. No entregaremos este resultado. Prueba una foto original más cercana y nítida.',
  PHOTO_LIKENESS_REJECTED:'El resultado no conservó suficientemente la referencia del rostro. No lo entregaremos. Prueba otra foto de frente y bien iluminada.',
  PHOTO_CONSENT_REQUIRED:'Hace falta aceptar el consentimiento del proveedor actual antes de generar. Vuelve a la selección de foto o pide al organizador que reactive tu acceso.',
  HF_AUTH_REQUIRED:'Falta conectar la cuenta gratuita de Hugging Face del organizador. Tu foto y tu acceso se conservan.',
  HF_FREE_ACCOUNT_REQUIRED:'El modo gratuito requiere una cuenta personal gratuita de Hugging Face. El organizador debe revisar la conexión.',
  QWEN_FREE_QUOTA:'Se agotó la cuota gratuita de Qwen. Espera a que Hugging Face la renueve o pide ayuda al organizador. Tu descarga sigue disponible.',
  QWEN_FREE_BUSY:'La GPU gratuita está ocupada. Inténtalo más tarde; tu descarga no se ha utilizado.',
  QWEN_FREE_UNAVAILABLE:'Hugging Face no pudo completar la generación gratuita. Puede haber cola o falta de cuota. Inténtalo más tarde.',
  PROVIDER_TIMEOUT:'La generación no terminó dentro del tiempo disponible. Inténtalo más tarde o contacta al organizador.',
  PHOTO_NEEDS_ONE_PERSON:'Elige una foto donde aparezcas solo tú. Así podemos integrarte correctamente en la escena.',
  PHOTO_FACE_UNCLEAR:'Tu rostro no se ve con suficiente claridad. Sube una foto nítida, de frente y con buena luz.',
  COMPOSITION_REJECTED:'La composición no superó la revisión de calidad. No entregamos ese montaje. Prueba con una foto más clara o pide ayuda al organizador.',
  QUALITY_CHECK_UNAVAILABLE:'No pudimos terminar la revisión de la foto. Vuelve a intentarlo en unos minutos.',
  ANALYSIS_INVALID:'No pudimos analizar bien las fotos. Inténtalo con otra foto individual y nítida.',
  PROVIDER_QUOTA:'El servicio de imágenes necesita saldo o cuota disponible. Contacta al organizador; tu descarga no se ha utilizado.',
  GEMINI_QUOTA:'El servicio de imágenes necesita cuota disponible. Contacta al organizador; tu descarga no se ha utilizado.',
  PROVIDER_SAFETY:'No se pudo procesar esta combinación de fotos. Selecciona una foto diferente o contacta al organizador.',
  PROVIDER_NOT_CONFIGURED:'El organizador debe activar un proveedor de generación de imágenes.',
  GEMINI_HTTP_404:'El organizador debe revisar qué modelo de Gemini está disponible en su proyecto.',
  GEMINI_HTTP_503:'El servicio de imágenes está ocupado. Inténtalo de nuevo en unos minutos.',
  GEMINI_NETWORK:'El análisis no pudo terminar a tiempo. Inténtalo de nuevo en unos minutos.',
  GEMINI_HTTP_400:'El organizador debe revisar la configuración del servicio de imágenes.',
  GEMINI_HTTP_401:'El organizador debe revisar las credenciales del servicio de imágenes.',
  GEMINI_HTTP_403:'El organizador debe revisar el acceso al servicio de imágenes.',
  PROVIDER_HTTP_401:'El organizador debe revisar las credenciales del servicio de imágenes.',
  PROVIDER_HTTP_403:'El organizador debe revisar el acceso al servicio de imágenes.',
 };
 return (code&&messages[code])||fallback;
}
